name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      shell: bash
      run: sudo apt-get install qt5-default

    - name: Make externals build dir
      shell: bash
      working-directory: ${{runner.workspace}}
      run: mkdir build

    - name: Build externals
      shell: bash
      working-directory: ${{runner.workspace}}/external/build
      run: cmake -DEXTERNAL_BUILD_TYPE=Release ..

    - name: Make externals
      shell: bash
      working-directory: ${{runner.workspace}}/external/build
      run: make

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release ..
        sudo make install

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
